### PR TITLE
Fix absolute path, and use one provider for the path. Closes #33

### LINKED ISSUE #33: outputPath should accept absolute paths
Right now if I want the downloads to go to a folder outside installation directory, it can be achieved by outputPath being "../whatever", but it should probably be an option to specify either absolute or relative path.

### PR DESCRIPTION
**Pull request by pmoranga**

### CODE REVIEW

File: class/FileHandler.php [hunk 1]
```diff
@@ -83,10 +83,10 @@ public function delete($id, $type)
 
 	private function outuput_folder_exists()
 	{
-		if(!is_dir($this->config['outputFolder']))
+		if(!is_dir($this->get_downloads_folder()))
 		{
 			//Folder doesn't exist
-			if(!mkdir('./'.$this->config['outputFolder'], 0777))
+			if(!mkdir($this->get_downloads_folder(),0777))
```
Comment (MatthewJohn) [inline class/FileHandler.php]: I know that you haven't changed the permissions, but is 777 really appropriate. 0755 might be better.

Comment (pmoranga) [inline class/FileHandler.php]: In my case, I would like to the owner of the webserver running user and
spawner of youtube-dl to have the write permission, and that my own user on
the box, had the right to manipulate the files as well without the need of
sudo'ing.

I know I could use setgid, but even them I would need assign myself into
webserver group or set this folder to a gid I own.
​

Comment (MatthewJohn) [inline class/FileHandler.php]: I think it would be safer to setup the directory as 0755, which would be owned by the webserver user. This doesn't stop the user from changing the permissions of the directory later to satisfy their needs, but as an initial configuration, I think this would probably be safer.
Hope that makes sense :)

Comment (pmoranga) [inline class/FileHandler.php]: ok, feel free to change it.

Pedro Moranga Gonçalves
pmoranga@gmail.com
+31 (0) 6 1206 0533

Comment (MatthewJohn) [inline class/FileHandler.php]: No problem - have forked, changed and created a pull request: #37
